### ISSUE TITLE
Images overlapping

### ISSUE THREAD

**Issue by robmarkcole** [asehmi/st-media-service#1]
As shown below:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/11855322/176984867-47aa6da2-4554-41be-872e-af6c449b21c5.png">

**Comment by asehmi** [comment]
Yep, configure grid layout presets in `.streamlit/secrets.toml` (used by `client_app.py`). My screen width is 2560 pixels wide, so the presets provided are set according to this screen width. Or uncheck the presets setting to manually adjust the columns and width.

**Comment by asehmi** [comment]
Hi @robmarkcole - I've added computed layout presets for different screen width resolutions. See the configuration section in the Readme.

**Comment by robmarkcole** [comment]
Awesome thanks @asehmi
